spring:
  application:
    name: "be"
  datasource:
    url: "jdbc:postgresql://dpg-cq4jo3eehbks73bcpv1g-a.singapore-postgres.render.com:5432/seedling"
    username: "seedling"
    password: "8gOJeGC71kiZqhNGmqwhZxCslVPXbuwQ"
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: 21124548@st.hcmuaf.edu.vn
    password: tyyb lzro flir wyzu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: "/api/v1"
  port: 8081

